### PR TITLE
Add output option for cli

### PR DESCRIPTION
**Pull request by brandonaaron**
Using stdout sometimes results in extra information (console.log statements) being included in the output. This adds an option for outputting the resulting CSS to a file rather than just stdout.

I was focused on getting my particular use-case satisfied. Let me know if I can do better/more.

### CODE REVIEW

**Comment by RyanZim** [comment]
> Using stdout sometimes results in extra information (console.log statements) being included in the output.

I'd argue that we should perhaps just fix these `console.log` statements, to ensure it's not included in the output. We should be only using `console.warn` and `console.error` to ensure any user-facing output goes to `stderr`.

**Comment by brandonaaron** [comment]
The `console.log` statements might be coming from scripts run on the page. Threw a quick gist together to illustrate: https://gist.github.com/brandonaaron/eda9710e6c570f55f45f513a9565ed5d

**Comment by RyanZim** [comment]
Ah, that's an interesting case. I'd still argue we should figure out how to configure JSDOM to output JS in-page `console.log`s to `stderr`.

**Comment by brandonaaron** [comment]
Yeah, perhaps that is a better option of handling this. Maybe just silence the `console.*` methods entirely? Otherwise, I believe we'd need to capture all the utility logging methods like `info`, `debug`, `table`, etc that just go to `stdout` as well.

**Comment by RyanZim** [comment]
> I believe we'd need to capture all the utility logging methods

That isn't too hard. We can use the core `console` module for this: https://nodejs.org/api/console.html

Example:
```js
virtualConsole: jsdom.createVirtualConsole().sendTo(new Console(process.stderr)),
```

**Comment by brandonaaron** [comment]
Another reason why I like having the output file option is so that I can overwrite the desired css file in place. For instance I'm using parcel as part of a build-chain and it finger prints the css file. So I used `find` to grab the finger printed css file to use as the output. I believe redirecting stdout will clear the file for writing before uncss gets the chance to parse it.

**Comment by RyanZim** [comment]
True; good points. I'm not opposed to adding an output option, but I think we also need to fix problems with stdout as well.

**Comment by brandonaaron** [comment]
Is there anything else I can do to get this PR and #385 merged?

**Comment by RyanZim** [comment]
https://github.com/uncss/uncss/pull/386#issuecomment-418382869

**Comment by brandonaaron** [comment]
Just wanted to follow up on this and #386. Anything else needed to get it merged?

**Comment by RyanZim** [comment]
I remain unconvinced this change is needed if https://github.com/uncss/uncss/pull/386 is merged and released. Not merging https://github.com/uncss/uncss/pull/386 myself since it needs review from the other collaborators here, and I don't have publish access to release it anyhow.

**Comment by brandonaaron** [comment]
Understood. Just want to highlight this [comment](https://github.com/uncss/uncss/pull/385#issuecomment-416615204) as justification for this PR for the other collaborators. 

I still have that use-case. The css file name is hashed and I want to overwrite the file in-place.

**Comment by giakki** [comment]
> I remain unconvinced this change is needed if #386 is merged and released. Not merging #386 myself since it needs review from the other collaborators here, and I don't have publish access to release it anyhow.

It is probably not needed, but I see no harm in giving the option to the users.

👍

**Pull request merged**
