### PR TITLE
Update to Postcss8

### PR DESCRIPTION
**Pull request by aminya**
This updates to postcss 8

The changes do not affect uncss
https://github.com/postcss/postcss/releases/tag/8.0.0

Closes https://github.com/uncss/uncss/pull/437

### CODE REVIEW

**Comment by aminya** [comment]
@giakki Could you take a look at this?

**Comment by giakki** [comment]
Apparently Github's web interface is not as smart as I hoped. could you please rebase against master? Thanks! 👍

**Comment by dannya** [comment]
@aminya @giakki  is this change fully intended, to put back in the `request` dependency when https://github.com/uncss/uncss/pull/426 had previously taken it out?

Since `request` is deprecated, it seems that the direction should be to keep it out of projects going forward.

**Comment by aminya** [comment]
No, I think it was re-added when the conflicts were resolved. The issue is fixed in #456, but @giakki hasn't reviewed it. See #459

**Pull request merged**
