### PR TITLE
Replace deprecated dependencies

### PR DESCRIPTION
**Pull request by NovaAtWarren**
Removed the outdated "request" package, and installed axios, including converting any existing usages that I could find. All tests passed except:

- Pages should resemble the reference: Bootstrap
- Pages should resemble the reference: Selectors

These seemed to be because chromium wouldn't install when running yarn install.

### CODE REVIEW

**Comment by NovaAtWarren** [comment]
It seems the CI is failing for OS compatibility reasons, instead of code, reasons, but if I'm wrong please tell me what I did that messed it up. Because I don't know.

**Comment by NovaAtWarren** [comment]
I would very much like this PR to be tested by someone on MacOS to assure my changes to fsevents usage doesn't break anything, and it's a MacOS only package.

**Review by aminya — APPROVED** [review]

**Comment by tomap** [comment]
I believe you need to update node min version to node 12 (due to jsdom)

**Comment by NovaAtWarren** [comment]
> I believe you need to update node min version to node 12 (due to jsdom)

Thank you very much, I'd completely missed that.

**Comment by NovaAtWarren** [comment]
Being honest, I should probably close this as it's pretty clear it's not going to merge at this point, and the branch I made it from has just become a fork.

**Comment by tomap** [comment]
I was thinking of using your fork to replace uncss. Seems much better

**Comment by NovaAtWarren** [comment]
> Seems much better

Just to clarify, I myself don't really see it as much better. It's barely had any changes from the master branch of this repo.
The difference is that it's still improving, where this one stagnated.
If it's useful though, and it does keep improving...

Well we'll see c:

**Pull request closed without merging**
