### PR TITLE
Inject

### PR DESCRIPTION
**Pull request by mikemellor11**
#131

### CODE REVIEW

**Comment by RyanZim** [comment]
I feel this is too localized. It's better to add an option which injects any arbitrary JS into the page.

**Comment by mikemellor11** [comment]
Would that option not be available as a command line parameter? I wasn't sure if that was too loose as an option giving too much control but i can look at changing it if you like.

**Comment by RyanZim** [comment]
@mikemellor11 I hadn't really thought that far. Perhaps the command line option would pass a filename containing the JS? i.e. `uncss index.html -I some.js`

**Comment by mikemellor11** [comment]
Yeah that would work, i guess my fix was more directed at my issue #327 which i would have thought was a much more common use case. The injecting js just leaves more setup/config for an uncss user rather than providing them with an easy option for a common use case? Just my two cents.

**Comment by mikemellor11** [comment]
Is this more what you had in mind?

**Comment by RyanZim** [comment]
Yeah. I feel this gives a significant amount of versatility to this option.

**Comment by mikemellor11** [comment]
Any updates on this? I'm currently including my fork as a git repo through npm and i'm hitting a few package-lock bugs. Could do with pointing it back at the published package.

**Comment by RyanZim** [comment]
@mikelambert has the publish bit; waiting on him to merge and publish a new version.

**Comment by mikelambert** [comment]
Sorry for the delay. :/ This should no be released as 0.16.2.

**Comment by XhmikosR** [comment]
I wonder, can we use `inject` to silence jsdom's errors? Basically I'm trying to ignore `URL.createObjectURL is not a function` uncaught TypeError.

**Pull request merged**
